version: "3"

vars:
  APP: lenslocked

tasks:
  build:
    desc: Build app with version
    cmds:
      - task: deps
      - go build -o {{.APP}} main.go

  test:
    desc: Run tests
    cmds:
      - task: deps
      - go test ./... {{.CLI_ARGS}}

  dev:
    desc: Run dev environment with PG
    cmds:
      - docker-compose up -d
      - modd

  exec:
    desc: Exec to PG DB
    cmds:
      - docker exec -ti lenslocked-db-1 psql -U baloo lenslocked

  deps:
    desc: Install dependencies
    cmds:
      - go mod tidy

  lint:
    desc: Run linter
    cmds:
      - golangci-lint run .